### ISSUE TITLE
EPIC: Define a mapping of Addressspace infos to OPC UA PubSub

### ISSUE THREAD

**Issue by DasbachVDMA** [umati/umatiGateway#51]
Define the topic structure and the UA JSON structure for the MQTT broker.

Preliminary discussions:
- Maybe reuse the browsepathes
- The approach must be repeatable for each OPC UA CS

@Kantiran91 Please make a appointment for a workshop

**Comment by Kantiran91** [comment]
2024-04-17:
Target of the topic structure + encoding:
The nodes defined by a type definition (from a Companion Specification) are transmitted in MQTT.

Requirements for the topic structure

- Be able to react to dynamic changes in the address space (nodes are added / nodes are deleted)
- Resolve pro-mans references (NodeId as values)
- Hierarchy references must be mapped
- No-hierachy references should be mapped if necessary
- Provide TypeInformation
- Methods should already be considered
- Online detection (possibly as separate topics)
- Objects that can be empty.
- Events / alarms must be able to be mapped
- Coordinate the completeness of the run
- The encoding should be UA JSON
- Dimensioning for approx. 350 subscribers (machines + dashboard users)
- Custom DataType must be included

Idea: Own dataset for publisher

- Gateway version
- Error message
- Status

**Comment by Kantiran91** [comment]
todos:
- [x] @Kantiran91 Read Part 14 and prepare a presentation 
- [x] Develop a draft for the topic structure
- [x] Make a workshop for defining the structure (@wlkrm @Kantiran91 @mdornaus @karstenroethig )

**Comment by Kantiran91** [comment]
ideas for mapping the Hierarchy references must be mapped:
- in topic structure (fit not good in opc ua standard)
- BrowsePath as Property in [MetaDataField](https://reference.opcfoundation.org/Core/Part14/v105/docs/6.2.3.2)
- Properties of [DataSetWriterProperties](https://reference.opcfoundation.org/Core/Part14/v105/docs/6.2.4.4)

ideas for mapping references to KeyValuePair:
Key (QualifiedName): Browsename of the ReferenceType
Value(NodeId): NodeId of the TargetValue

**Comment by Kantiran91** [comment]
Here is a wiki article that contain all infos for this discussion:
https://github.com/umati/UA-CloudPublisher/wiki/Recommendations-for-Mapping-OPC-UA-Addessspace-information-in-OPC-UA-Pub-Sub

**Comment by Kantiran91** [comment]
@mdornaus @wlkrm @GoetzGoerisch @karstenroethig @ccvca 
I have create an draft for the Pub/Sub Spec of the Dashboard. 
Can you please review the document?

https://github.com/umati/UA-CloudPublisher/pull/54

**Comment by ccvca** [comment]
![grafik](https://github.com/umati/UA-CloudPublisher/assets/3939648/5ac5bb1e-13a2-4775-b2d6-213c74538b82)

https://reference.opcfoundation.org/Core/Part3/v105/docs/5.2.4

There is also no rule, that BrowseNames must not contain any of the following characters: `./:`

**Comment by Kantiran91** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/3939648/344144715-5ac5bb1e-13a2-4775-b2d6-213c74538b82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzYwNjgsIm5iZiI6MTcxOTU3NTc2OCwicGF0aCI6Ii8zOTM5NjQ4LzM0NDE0NDcxNS01YWM1YmIxZS0xM2EyLTQ3NzUtYjJkNi0yMTNjNzQ1MzhiODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMTE1NjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmFhMGNjMTNmZjJiODUyZWU3NDE4MDI3ODYyYTE5YjA0ZWM5YWJlZDcyY2UyNDY5ZDI4MDRmYzU0ZDI3YTRlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VZFiHOk_R5LsO0zRudLTBhUffCSeR9aIzUUHR-xfXv8)
> 
> https://reference.opcfoundation.org/Core/Part3/v105/docs/5.2.4
> 
> There is also no rule, that BrowseNames must not contain any of the following characters: `./:`

Yes that why we use the BrowsPath as name which can be used for intentify. 

If you flow the annex of Part 4 the character are not allowed:
https://reference.opcfoundation.org/Core/Part4/v105/docs/A

Do you suggest that we give a hint how to solve BrowsePath conflicts? e.g. allowing to add an iteration value?

**Comment by ccvca** [comment]
`/` is allowed, ist just needs to be prefixed by a `&`, which will screw up MQTT as well.

```
<name>::= (<name-char> | '&' <reserved-char>) [<name>]
<reserved-char>::= '/' | '.' | '<' | '>' | ':' | '#' | '!' | '&' 
<name-char> ::= All valid characters for a String (see [OPC 10000-3](https://reference.opcfoundation.org/Core/Part3/v105/docs/)) excluding reserved-chars.
```

In the current version, this is solved by an URL-Encoding using an underscore instead of a '%'.

**Comment by GoetzGoerisch** [comment]
fiexed with https://github.com/umati/umatiGateway/blob/develop/requirements/specification.md
