### ISSUE TITLE
EPIC: Extend the Cloud Publisher with an ObjectType selection

### ISSUE THREAD

**Issue by Kantiran91** [umati/umatiGateway#52]
Enable to select entire ObjectTypes within the the cloudpublisher. Every instance of this ObjectType will be transfered via pub sub.

Todo: 

- [ ] umati/UA-CloudPublisher#44 
- [ ] umati/UA-CloudPublisher#45 
- [ ] umati/UA-CloudPublisher#46 
- [ ] umati/UA-CloudPublisher#47 
- [ ] umati/UA-CloudPublisher#48

**Comment by Kantiran91** [comment]
@mdornaus Can you add some subtaks as issues to this epic?

**Comment by mdornaus** [comment]
Closed. Decided to create own gateway.
